<template>
    <div class="playlist">
        <AddSong @close="updatePlaylist" ref="addSongPopup"/>
        <EditPlaylist
            @close="updatePlaylist"
            :playlist="{
                name: playlistName,
                description: playlistDescription,
                cover: playlistCover,
                id
            }"
            ref="editPlaylistPopup"/>
        <fixed-playlist-header
            @loadPlaylist="loadPlaylist"
            ref="fixedHeading"
            :class="{ 'hidden': fixedHeaderHidden }"
            :title="playlistName"
        />
        <div class="padding-20 playlisteditor" @click="editPlaylist" v-observe-visibility="headerVisibilityChanged">
            <Cover :src="playlistCover" type="playlist" />
            <div class="details">
                <h1>{{ playlistName }}</h1>
                <h6>{{ playlistDescription }}</h6>
                <p class="muted description">{{ autogeneratedDescription }}</p>
            </div>
        </div>
        <div class="mobileMenu showIfMobile">
            <span @click="() => $emit('toggleFullSidebar')" class="material-symbols-rounded">menu</span>
        </div>
        <hr>
        <div class="padding-20">
            <span id="loadPlaylist" @click="loadPlaylist" class="material-symbols-rounded">play_circle</span>
            <span id="addToPlaylist" @click="addToPlaylist" class="material-symbols-rounded">add_circle</span>
            <div class="grid">
                <PlaylistHeader
                    class="hideIfMobile"
                    with-more
                />
                <hr>
                <div class="playlistEntries">
                    <draggable v-model="playlist" @change="onPlaylistRearrange">
                        <template #item="{element}">
                            <PlaylistEntry
                                :index="playlist.findIndex(x => x.source == element.source)"
                                :song="element"
                                with-cover
                                with-album
                                with-more
                                :playlist-id="Number(id)"
                                @click="selectedSongId == element.id ? selectedSongId = -1 : selectedSongId = element.id"
                                @update="updatePlaylist"
                                :selected="selectedSongId == element.id"
                            />
                        </template>
                    </draggable>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import FixedPlaylistHeader from '../components/Playlist/FixedPlaylistHeader.vue'
import PlaylistEntry from '../components/songContainers/PlaylistEntry.vue'
import PlaylistHeader from '../components/songContainers/PlaylistHeader.vue'
import AddSong from "../components/popups/AddNewSong.vue"
import EditPlaylist from '../components/popups/EditPlaylist.vue'
import draggable from 'vuedraggable'
import Cover from '@/components/image/Cover.vue'

import {hashPlaylist, parseCover, parsePlaylistCover, unhashPlaylist} from "@/common";
import {usePlayerStore} from "@/store/player";
import {createPlaylist, getPlaylist} from "@/api/playlist";
import {useDataStore} from "@/store/data";

const data = useDataStore();


export default {
    components: {
        PlaylistEntry,
        FixedPlaylistHeader,
        PlaylistHeader,
        AddSong,
        EditPlaylist,
        draggable,
        Cover
    },
    name: 'Playlist',
    data() {
        this.updatePlaylist()

        return {
            fixedHeaderHidden: true,
            playlist: [],
            playlistName: "N/A",
            playlistDescription: "",
            playlistCover: null,
            store: usePlayerStore(),
            selectedSongId: -1,
        }
    },
    methods: {
        parseCover,
        parsePlaylistCover,
        download(index) {
            const data = this.playlist?.[index]
            window.open(`/api/tracks/${data.id}/download`)
        },
        onPlaylistRearrange(type) {
            const moved = type.moved

            if (!moved) {
                return;
            }

            fetch(`/api/playlists/${this.id}/tracks`, {
                method: "PUT",
                body: JSON.stringify({
                    songOldIndex: moved.oldIndex,
                    songNewIndex: moved.newIndex
                })
            })
        },
        headerVisibilityChanged(a) {
            this.fixedHeaderHidden = a
        },
        addToPlaylist() {
            this.$refs.addSongPopup.show();
        },
        editPlaylist() {
            this.$refs.editPlaylistPopup.show();
        },
        updateIsPlaying() {
            this.playlist.forEach((element) => {
                element.playing = element.id == this.currentSong
            })
        },
        updatePlaylist() {
            if (!this.id) {
                return
            }
            if (!this.$route.path.includes("/playlist/")) {
                return;
            }

            if (this.$route.params.id == "create") {
                createPlaylist().then(id => {
                    const link = hashPlaylist(id);
                    this.$router.push(link);
                })
                return
            }
            getPlaylist(this.id).then(async jdata => {
                if (!jdata) {
                    this.$router.push("/")
                    return
                }

                this.playlist = jdata.songs
                this.playlistName = jdata.name
                this.playlistDescription = jdata.description
                this.playlistCover = jdata.cover
                document.title = `${this.playlistName} - reAudioPlayer One`;
                this.updateIsPlaying()
            })
        },
        loadPlaylist() {
            fetch("/api/player/load", {
                method: "POST",
                body: JSON.stringify({
                    id: Number(this.id),
                    type: "playlist"
                })
            })
        }
    },
    computed: {
        id() {
            return unhashPlaylist(this.$route.params.id)
        },
        autogeneratedDescription() {
            return `${this.playlist.length} ${this.playlist.length == 1 ? "song" : "songs"}${this.estimatedDuration}`
        },
        currentSong() {
            return this.store.song.id;
        },
        estimatedDuration() {
            let duration = 0;
            let isEstimate = false;

            if (!this.playlist.length) {
                return "";
            }

            for (const song of this.playlist) {
                isEstimate = isEstimate || ("-1:59" == song.duration);
                const songDurString = song.duration == "-1:59" ? "3:00" : song.duration; // estimate 3:00 if unknown
                const [min, sec] = songDurString.split(":")
                duration += Number(min * 60) + Number(sec);
            }

            const sec = duration;
            const min = Math.floor(sec / 60);
            const hs = Math.floor(min / 60);

            const prefix = isEstimate ? ", about " : ", "

            if (hs) {
                return prefix + `${hs} hr ${min - hs * 60} min`
            }

            if (min) {
                return prefix + `${min} min ${sec - min * 60} sec`
            }

            return prefix + duration + " sec";
        }
    },
    mounted() {
        this.updatePlaylist()
    },
    watch: {
        $route() {
            this.updatePlaylist()
        },
        currentSong() {
            this.updateIsPlaying()
        }
    }
}
</script>

<style scoped lang="scss">
$mobileWidth: 950px;

.playlisteditor img {
    width: 15%;
    margin-right: 20px;
    border-radius: 5px;
}

.playlisteditor {
    display: flex;
    flex-direction: row;
    margin-bottom: 20px;
    margin-top: 5vh;

    @media screen and (max-width: $mobileWidth) {
        flex-direction: column;

        img {
            align-self: center;
            width: 40%;
        }
    }
}

.playlisteditor .details {
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
}

.playlisteditor:hover {
    cursor: pointer;
}

#loadPlaylist,
#addToPlaylist {
    cursor: pointer;
    font-size: 60px;
    margin-bottom: 20px;
    width: 70px;
    line-height: 70px;
    text-align: center;
    align-items: center;
    vertical-align: middle;
}

#loadPlaylist:hover, #addToPlaylist:hover {
    cursor: pointer;
    font-size: 62px;
}

.padding-20 {
    padding: 20px;
}

h3 {
    text-transform: uppercase;
}

h7 {
    text-transform: uppercase;
    font-weight: bold;
    font-size: 0.83em;
}

h1 {
    margin-block-start: 0.15em;
    margin-block-end: 0.15em;
    font-size: 2.91em;

    @media screen and (max-width: $mobileWidth) {
        font-size: 1.4em;
        margin-top: 10px;
        margin-bottom: 0;
        margin-block-end: 0;
    }
}

.hidden {
    display: none !important;
}

h6 {
    color: var(--font-darker);
    font-weight: normal;
    margin-bottom: 10px;

    @media screen and (max-width: $mobileWidth) {
        margin-top: 0;
    }
}

p.muted.description {
    color: var(--font-darker);
    font-weight: normal;
    font-size: .7em;
    margin: 0;
}
</style>