<script setup>
import {usePlayerStore} from "@/store/player";
import {computed} from "vue";

const playerStore = usePlayerStore();
const currentSong = computed(() => playerStore.song.id);
</script>

<template>
    <div class="playlist">
        <AddSong @close="updatePlaylist" ref="addSongPopup"/>
        <EditPlaylist @close="updatePlaylist" :playlistCover="playlistCover" :playlistName="playlistName"
                      :playlistDescription="playlistDescription" ref="editPlaylistPopup"/>
        <fixed-playlist-header
            @loadPlaylist="loadPlaylist"
            ref="fixedHeading"
            :class="{ 'hidden': fixedHeaderHidden }"
            :title="playlistName"
        />
        <div class="padding-20 playlisteditor" @click="editPlaylist" v-observe-visibility="headerVisibilityChanged">
            <img v-if="playlistCover" class="cover" :src="playlistCover"/>
            <div class="details">
                <h7 class="hideIfMobile">Playlist</h7>
                <h1>{{ playlistName }}</h1>
                <h5>{{ playlistDescription }}</h5>
                <p class="muted description">{{ autogeneratedDescription }}</p>
            </div>
        </div>
        <div class="mobileMenu showIfMobile">
            <span @click="() => $emit('toggleFullSidebar')" class="material-symbols-rounded">menu</span>
        </div>
        <hr>
        <div class="padding-20">
            <span id="loadPlaylist" @click="loadPlaylist" class="material-symbols-rounded">play_circle</span>
            <span id="addToPlaylist" @click="addToPlaylist" class="material-symbols-rounded">add_circle</span>
            <div class="grid">
                <grid-header class="hideIfMobile"/>
                <hr>
                <div class="playlistEntries">
                    <draggable v-model="playlist" @change="onPlaylistRearrange">
                        <template #item="{element}">
                            <playlist-entry
                                :playlists="playlists"
                                @download="download"
                                @requestUpdate="updatePlaylist"
                                :index="playlist.findIndex(x => x.source == element.source)"
                                :source="element.source"
                                :playing="element.playing"
                                :id="element.id"
                                :title="element.title"
                                :album="element.album"
                                :artist="element.artist"
                                :cover="element.cover"
                                :favourite="element.favourite"
                                :duration="element.duration"
                            />
                        </template>
                    </draggable>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import FixedPlaylistHeader from '../components/Playlist/FixedPlaylistHeader.vue'
import GridHeader from '../components/Playlist/GridHeader.vue'
import PlaylistEntry from '../components/Playlist/PlaylistEntry.vue'
import AddSong from "../components/Popups/AddSong.vue"
import EditPlaylist from '../components/Popups/EditPlaylist.vue'
import draggable from 'vuedraggable'
import {hashPlaylist, unhashPlaylist} from "@/common";


export default {
    components: {
        PlaylistEntry,
        FixedPlaylistHeader,
        GridHeader,
        AddSong,
        EditPlaylist,
        draggable
    },
    name: 'Playlist',
    data() {
        this.updatePlaylist()

        fetch("/api/playlists").then(x => x.json()).then(jdata => {
            this.playlists = jdata
        })

        return {
            fixedHeaderHidden: true,
            playlist: [],
            playlistName: "N/A",
            playlistDescription: "",
            playlistCover: null,
            playlists: []
        }
    },
    methods: {
        getId() {
            return unhashPlaylist(this.$route.params.id);
        },
        download(index) {
            const data = this.playlist?.[index]
            window.open(`/api/tracks/${data.id}/download`)
        },
        onPlaylistRearrange(type) {
            const moved = type.moved

            if (!moved) {
                return;
            }

            fetch(`/api/playlists/${this.getId()}/tracks`, {
                method: "PUT",
                body: JSON.stringify({
                    songOldIndex: moved.oldIndex,
                    songNewIndex: moved.newIndex
                })
            })
        },
        headerVisibilityChanged(a) {
            this.fixedHeaderHidden = a
        },
        addToPlaylist() {
            this.$refs.addSongPopup.showModal = true
        },
        editPlaylist() {
            this.$refs.editPlaylistPopup.showModal = true
        },
        updateIsPlaying() {
            this.playlist.forEach((element) => {
                element.playing = element.id == this.currentSong
            })
        },
        updatePlaylist() {
            if (!this.getId()) {
                return
            }
            if (!this.$route.path.includes("/playlist/")) {
                return;
            }

            if (this.$route.params.id == "create") {
                fetch("/api/playlists/new")
                    .then(x => x.text()).then(y => {
                        const link = hashPlaylist(y);
                        this.$router.push(link)
                })
                return
            }
            fetch(`/api/playlists/${this.getId()}`).then(async x => {
                if (x.status == 404) {
                    this.$router.push("/")
                    return
                }

                const jdata = await x.json()
                this.playlist = jdata.songs
                this.playlistName = jdata.name
                this.playlistDescription = jdata.description
                this.playlistCover = jdata.cover
                document.title = `${this.playlistName} - reAudioPlayer One`;
                this.updateIsPlaying()
            })
        },
        loadPlaylist() {
            fetch("/api/player/load", {
                method: "POST",
                body: JSON.stringify({
                    id: Number(this.getId()),
                    type: "playlist"
                })
            })
        }
    },
    computed: {
        autogeneratedDescription() {
            return `${this.playlist.length} ${this.playlist.length == 1 ? "song" : "songs"}${this.estimatedDuration}`
        },
        estimatedDuration() {
            let duration = 0;
            let isEstimate = false;

            if (!this.playlist.length) {
                return "";
            }

            for (const song of this.playlist) {
                isEstimate = isEstimate || ("-1:59" == song.duration);
                const songDurString = song.duration == "-1:59" ? "3:00" : song.duration; // estimate 3:00 if unknown
                const [min, sec] = songDurString.split(":")
                duration += Number(min * 60) + Number(sec);
            }

            const sec = duration;
            const min = Math.floor(sec / 60);
            const hs = Math.floor(min / 60);

            const prefix = isEstimate ? ", about " : ", "

            if (hs) {
                return prefix + `${hs} hr ${min - hs * 60} min`
            }

            if (min) {
                return prefix + `${min} min ${sec - min * 60} sec`
            }

            return prefix + duration + " sec";
        }
    },
    mounted() {
        this.updatePlaylist()
    },
    watch: {
        $route() {
            this.updatePlaylist()
        },
        currentSong() {
            this.updateIsPlaying()
        }
    }
}
</script>

<style scoped lang="scss">
$mobileWidth: 950px;

.playlisteditor img {
    width: 15%;
    margin-right: 20px;
    border-radius: 5px;
}

.playlisteditor {
    display: flex;
    flex-direction: row;
    margin-bottom: 20px;
    margin-top: 5vh;

    @media screen and (max-width: $mobileWidth) {
        flex-direction: column;

        img {
            align-self: center;
            width: 40%;
        }
    }
}

.playlisteditor .details {
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
}

.playlisteditor:hover {
    cursor: pointer;
}

.playlistEntries {
    display: flex;
    flex-direction: column;
}

#loadPlaylist,
#addToPlaylist {
    cursor: pointer;
    font-size: 60px;
    margin-bottom: 20px;
    width: 70px;
    line-height: 70px;
    text-align: center;
    align-items: center;
    vertical-align: middle;
}

#loadPlaylist:hover, #addToPlaylist:hover {
    cursor: pointer;
    font-size: 62px;
}

.padding-20 {
    padding: 20px;
}

h3 {
    text-transform: uppercase;
}

h7 {
    text-transform: uppercase;
    font-weight: bold;
    font-size: 0.83em;
}

h1 {
    margin-block-start: 0.15em;
    margin-block-end: 0.15em;
    font-size: 2.91em;

    @media screen and (max-width: $mobileWidth) {
        font-size: 1.4em;
        margin-top: 10px;
        margin-bottom: 0;
        margin-block-end: 0;
    }
}

.hidden {
    display: none !important;
}

h5 {
    color: var(--font-darker);
    font-weight: normal;
    margin-bottom: 10px;

    @media screen and (max-width: $mobileWidth) {
        margin-top: 0;
    }
}

p.muted.description {
    color: var(--font-darker);
    font-weight: normal;
    font-size: .7em;
    margin: 0;
}
</style>